### PR TITLE
143 Update Registry Resolver Client With Spec Compliant Version

### PR DESCRIPTION
**Pull request by LuisOsta**

### CODE REVIEW

**Comment by LuisOsta** [comment]
@adewaleafolabi In the client right now we just return the Did Document, what do you think the value is of returning the other things that are part of the `resolve` response?

**Comment by LuisOsta** [comment]
The steps after this PR is done is to:

- Create a new SSI release
- Update CW to work with new release (setup PR)
- Merge Gomono Registry Mgmt PR
- Merge CW PR

**Comment by adewaleafolabi** [comment]
> @adewaleafolabi In the client right now we just return the Did Document, what do you think the value is of returning the other things that are part of the `resolve` response?

The resolve response according to the spec must contain three objects 

- didResolutionMetadata
- didDocument
- didDocumentMetadata

image

For SSI, if we don't need those other items we can just skip it for now. They are basically metadata

**Comment by LuisOsta** [comment]
@adewaleafolabi Alright sounds good, the question was more about what we did or didn't want to expose. For something this low level it makes sense to expose everything

**Comment by LuisOsta** [comment]
@adewaleafolabi Are the values in `didUrl` in resolution metadata optional or required?

**Review by adewaleafolabi — APPROVED** [review]

**Pull request merged**
